const RoleName = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  LAND_MANAGER: "LAND_MANAGER",
  STS_MANAGER: "STS_MANAGER",
  UNASSIGNED: "UNASSIGNED",
  CONTRACTOR_MANAGER: "CONTRACTOR_MANAGER",
  CONTRACTOR_EMPLOYEE: "CONTRACTOR_EMPLOYEE",
};

export { RoleName };
